### ISSUE TITLE
RNN Sampling Code

### ISSUE THREAD

**Issue by srush** [srush/annotated-s4#11]
Sampling code currently works for MNist. However it uses the CNN version which is really slow. We should have a way to turn any of our sequence models into an RNN model. 

Also my way of generating images is to average the predictions, which is a bit blurry. Maybe there is a better way?

**Comment by siddk** [comment]
Albert/Karan mentioned severe stability issues when turning the convolution into a recurrence to use for sampling (when applied to audio, longer sequence lengths... they didn't try sampling on MNIST or CIFAR).

Worth keeping in mind...

**Comment by siddk** [comment]
Closed by #43
