### ISSUE TITLE
Question, why does the reshape function has no argument?

### ISSUE THREAD

**Issue by AliceSum** [srush/annotated-s4#41]
Hi. I see the reshape function does not take arguments.
![image](https://user-images.githubusercontent.com/21982975/149792049-94c50e7d-7761-4b94-8f05-62bdfe04199e.png)
I guess this is not an error. If so, can someone explain to me what shape it is going to have from the original shape?

**Comment by srush** [comment]
It just turns it into a jax scalar

import jax.numpy as np
np.array([1]).reshape().shape
> ()

This function could be written in a much more efficient way, just wanted to show it in a non-matrix style.

**Comment by AliceSum** [comment]
Thx for answering. But It is just "_reshape()_" in the code, not "_reshape().shape_"

**Comment by srush** [comment]
I was just showing that the shape is () after reshape, i.e. scalar
