### ISSUE TITLE
typos in blog

### ISSUE THREAD

**Issue by qsh-zh** [srush/annotated-s4#54]
Thanks for your awesome blogs,

I notice there may be some typos in the blog,
1. 
![image](https://user-images.githubusercontent.com/28699575/165374471-f129db2b-7f96-4607-b653-1e33b0113370.png)

The term $q^*p$ should be $q^* \Gamma^{-1}p$.

2. 
![image](https://user-images.githubusercontent.com/28699575/165374907-7b71ad36-dc0a-40b3-9247-6f1d3e507016.png)
If we follow the assumption that $A=\Gamma - p^*q$ the $1-k_{z,\Gamma}(q^*, p)$ should be $1+k_{z,\Gamma}(q^*, p)$.

3. (may be not a typo)
![image](https://user-images.githubusercontent.com/28699575/165375287-645f4205-9aa9-467a-8f22-36aed8c147ed.png)
The decomposition for $A$ should be $\Gamma - p^*q$ (maybe authors want to use $\Gamma + p^*q$  for the introduction of Woodbury.

**Comment by srush** [comment]
Thanks. Yes, these are incorrect. Will update.
