### ISSUE TITLE
conj() is used when the equation doesn't specify it

### ISSUE THREAD

**Issue by ratishsp** [srush/annotated-s4#74]
Hi, 
why do we use conj() in the code below when the equation doesn't specify it:
![image](https://github.com/srush/annotated-s4/assets/3006607/87a23b9f-ae3d-46b7-b091-5cdffd6061dc)

```
def K_gen_inverse(Ab, Bb, Cb, L):
    I = np.eye(Ab.shape[0])
    Ab_L = matrix_power(Ab, L)
    Ct = Cb @ (I - Ab_L)
    return lambda z: (Ct.conj() @ inv(I - Ab * z) @ Bb).reshape()
```

**Comment by albertfgu** [comment]
Notation and code doesn't have to map 1-1. Things can be defined in whatever way is simpler. In other words, just think of $\overline{\boldsymbol{C}}$ in the equation to be represented by `Ct.conj()` in the code.

You do need to pay close attention to all the conjugates to get the implementation exactly right. See also the original paper (appendix C.3), in particular this comment:
![image](https://github.com/srush/annotated-s4/assets/8164679/bfd4cc0f-6cfa-43e7-8d4f-b9f7b15be48c)

**Comment by ratishsp** [comment]
Ah, it now makes sense. Thanks again!
